### ISSUE TITLE
[BUG] La aplicación crashea al estar en portrait

### ISSUE THREAD

**Issue by NEKERAFA** [gymkhanachain/GymkhanaChain#7]
**Describe the bug**
Las actividades que no son el MainActivity no tienen activada la opción de quitar el estado de portrait, por lo que cuando pasas a la actividad principal esta peta completamente.

**Expected behavior**
Se esperaba que todas las actividades fueran en modo portrait y no petasen

**Smartphone:**
 - OS version: Android 8.1

**Comment by Aletibazo** [comment]
Solved on commit 3db7424dac241617f407ac4614ebd202df721b42. 

Must always add android:screenOrientation="portrait" on <activity .../> block on Manifest.xml when creating a new Activity.
